service:
  name: Surveyor
plugins:
  - serverless-webpack
  - serverless-alexa-skills

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  environment:
    CLIENT_SECRET: ${file(./config/${self:provider.stage}.yml):CLIENT_SECRET}
    CLIENT_ID: ${file(./config/${self:provider.stage}.yml):CLIENT_ID}
    STAGE: ${file(./config/${opt:stage, 'development'}.yml):STAGE}
    CALLBACK_URL: ${file(./config/${self:provider.stage}.yml):CALLBACK_URL}
custom:
  alexa:
    # Step 1: Run `sls alexa auth` to authenticate
    # Step 2: Run `sls alexa create --name "Serverless Alexa Typescript" --locale en-GB --type custom` to create a new skill
    skills:
      # Step 3: Paste the skill id returned by the create command here:
      - id: ${file(./config/${self:provider.stage}.yml):SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              en-US:
                name: Kumu - DEV
          apis:
            custom:
              endpoint:
                # Step 4: Do your first deploy of your Serverless stack
                # Step 5: Paste the ARN of your lambda here:
                uri: ${file(./config/${self:provider.stage}.yml):ENDPOINT_URI}
                # Step 6: Run `sls alexa update` to deploy the skill manifest
                # Step 7: Run `sls alexa build` to build the skill interaction model
                # Step 8: Enable the skill in the Alexa app to start testing.
          manifestVersion: '1.0'
        models:
          en-GB:
            interactionModel:
              languageModel:
                invocationName: serverless typescript
                intents:
                  - name: HelloIntent
                    samples:
                      - 'hello'

functions:
  alexa:
    handler: handler.alexa
    events:
      - alexaSkill: ${self:custom.alexa.skills.0.id}